port: 28080
log-level: debug
buffer-size: 1000
#kafka服务器
kafka:
  broker-list:
    - 10.122.94.94:9192
  group-id: log-kit-group
  topic-name: log_kit
#es服务
elastic:
  url: https://10.122.94.94:9200
  username: elastic
  password: xoESLDqdYh5

#日志源
source:
  file-source:
    - app-id: demo1
      path: /Users/yihongzhi/Downloads/current.log_galaxy_analysis-1_20220106_13.log
      multiline:
        enable: true
        pattern: '^[0-2][0-9][0-9][0-9]-[0-5][0-9]-[0-5][0-9]'
#解析器
analyzer:
  parser:
    - app-id: demo1
      type: regex
      pattern: '(.+)\s-\s(\w+)\s\[TxId\s:(.+),\sSpanId\s:(.+)].+\[(.+)]\s(\S+)\s+:\s(.+)'
      field: [ "time", "level", "tx_id", "span_id", "thread", "method", "content" ]